"""
Forecast integration.

Proprietary forecasting runs in a private analysis service. This public module
keeps only the API contract required by the UI.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from services.analysis_engine import AnalysisEngineError, dataframe_payload, post_engine


DEFAULT_HORIZON = 12
FORECAST_HORIZONS = {
    "1D": 1,
    "3D": 3,
    "1W": 5,
    "12D": 12,
    "1M": 21,
    "1Y": 252,
}


@dataclass(frozen=True)
class TimesFMForecast:
    available: bool
    message: str
    message_key: str | None = None
    message_params: dict | None = None
    horizon: int = DEFAULT_HORIZON
    last_price: float | None = None
    model_target: float | None = None
    scenario_target: float | None = None
    model_return_pct: float | None = None
    scenario_return_pct: float | None = None
    trend_return_pct: float | None = None
    news_label: str = "Neutral"
    direction: str = "Neutral"
    dates: list[pd.Timestamp] | None = None
    model_values: list[float] | None = None
    scenario_values: list[float] | None = None
    lower_80: list[float] | None = None
    upper_80: list[float] | None = None


def _unavailable(message: str, horizon: int) -> TimesFMForecast:
    return TimesFMForecast(
        available=False,
        message=message,
        message_key="forecast.messages.private_engine_unavailable",
        message_params={"reason": message},
        horizon=horizon,
    )


def normalize_forecast_horizon(horizon: int | str | None) -> int:
    try:
        parsed = int(horizon) if horizon is not None else DEFAULT_HORIZON
    except (TypeError, ValueError):
        parsed = DEFAULT_HORIZON

    valid = set(FORECAST_HORIZONS.values())
    return parsed if parsed in valid else DEFAULT_HORIZON


def _forecast_from_response(data: dict, horizon: int) -> TimesFMForecast:
    dates = data.get("dates")
    parsed_dates = [pd.Timestamp(date) for date in dates] if isinstance(dates, list) else None
    return TimesFMForecast(
        available=bool(data.get("available", True)),
        message=str(data.get("message") or "Forecast generated by private analysis engine."),
        message_key=data.get("message_key"),
        message_params=data.get("message_params"),
        horizon=int(data.get("horizon") or horizon),
        last_price=data.get("last_price"),
        model_target=data.get("model_target"),
        scenario_target=data.get("scenario_target"),
        model_return_pct=data.get("model_return_pct"),
        scenario_return_pct=data.get("scenario_return_pct"),
        trend_return_pct=data.get("trend_return_pct"),
        news_label=str(data.get("news_label") or "Neutral"),
        direction=str(data.get("direction") or "Neutral"),
        dates=parsed_dates,
        model_values=data.get("model_values"),
        scenario_values=data.get("scenario_values"),
        lower_80=data.get("lower_80"),
        upper_80=data.get("upper_80"),
    )


def build_timesfm_forecast(
    df: pd.DataFrame,
    news_list: list[dict],
    horizon: int = DEFAULT_HORIZON,
) -> TimesFMForecast:
    horizon = normalize_forecast_horizon(horizon)
    payload = {
        "horizon": horizon,
        "history": dataframe_payload(df),
        "news": news_list,
    }

    try:
        response = post_engine("/forecast", payload)
    except AnalysisEngineError as exc:
        return _unavailable(str(exc), horizon)

    return _forecast_from_response(response, horizon)
